name: Build CI - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make -C Project/3_Implementation
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
